apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
- name: cloudnative-pg
  repo: https://cloudnative-pg.github.io/charts
  version: 0.27.0
  releaseName: cnpg
  namespace: cnpg-system
  valuesFile: ../../base/values.yaml
  valuesMerge: override
  additionalValuesFiles:
    - values.yaml
