apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.1.6
    releaseName: argocd
    namespace: argocd
    valuesFile: ../../base/values.yaml
    valuesMerge: override # merge strategy, default is strategic
    additionalValuesFiles:
      - values.yaml

namespace: argocd
resources:
  - http-route.yaml
