apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ip-pool.yml

helmCharts:
  - name: cilium
    releaseName: cilium
    repo: https://helm.cilium.io
    version: 1.18.6
    valuesFile: values.yaml
    namespace: kube-system
