name: Renovate
# This workflow is used to run Renovate to keep dependencies up to date.
# It is triggered manually or on a schedule.
# The Renovate configuration is stored in .github/renovate/number2.json.
# The Renovate token is stored in the repository secrets as RENOVATE_TOKEN.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,18 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['renovate']
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: renovatebot/github-action@6927a58a017ee9ac468a34a5b0d2a9a9bd45cac3 # v43.0.11
        name: Run Renovate (${{ matrix.env }})
        with:
          configurationFile: ${{ matrix.env }}.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
