name: Renovate
# This workflow is used to run Renovate to keep dependencies up to date.
# It is triggered manually or on a schedule.
# The Renovate configuration is stored in .github/renovate/number2.json.
# The Renovate token is stored in the repository secrets as RENOVATE_TOKEN.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,18 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['renovate']
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: renovatebot/github-action@ea850436a5fe75c0925d583c7a02c60a5865461d # v43.0.20
        name: Run Renovate (${{ matrix.env }})
        with:
          configurationFile: ${{ matrix.env }}.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
